baseurl = "https://shanonana.github.io/"
canonifyURLs = true
disqusShortname = "shortname"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect"
title = "Rock Foxes"
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
identifier = "fa fa-list"
name = "Itemized"
url = "/itemized/"
weight = 4
[[menu.main]]
identifier = "fa fa-sitemap"
name = "Categories"
url = "/categories/"
weight = 5
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact"
url = "/contact/"
weight = 6
[params]
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"
categoriesByCount = true
customCSS = ["default"]
customJS = ["default"]
description = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
disable_highlight = false
dynamicTitles = true
faviconVersion = ""
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "css"]
highlightjsTheme = "github"
highlightjsVersion = "9.11.0"
includeReadingTime = true
loadFavicon = false
navbarTitle = "Rocks & Foxes"
rssAppearAtBottom = true
rssAppearAtTop = true
showSidebarCategories = true
socialAppearAtBottom = true
socialAppearAtTop = true
socialShare = true
socialShareEmail = true
socialShareFacebook = false
socialShareGoogleplus = false
socialShareLinkedin = false
socialSharePinterest = false
socialShareReddit = false
socialShareStumbleupon = false
socialShareTwitter = false
viewMorePostLink = "/blog/"
[params.intro]
about = "I climb, I listen, and I take care of my rescue dog. Hear me out."
header = "Rock Foxes"
paragraph = "A box of thoughts conjured by Shannon Suarez <i class='fa fa-hand-peace-o'></i>"
[params.intro.pic]
alt = "Rock Foxes"
circle = true
imperfect = false
src = "/img/main/logo.jpg"
width = ""
[params.postAmount]
sidebar = 5
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = "sgsuarez1@gmail.com"
facebook = ""
flickr = ""
foursquare = ""
github = ""
gitlab = ""
googleplus = ""
googlescholar = ""
instagram = "shuppo_shan"
jsfiddle = ""
linkedin = ""
linkedin_company = ""
medium = ""
orcid = ""
pinterest = ""
qq = ""
quora = ""
reddit = ""
researchgate = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
telegram = ""
tumblr = ""
twitter = ""
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
